INSERT
INTO
  cfg_app
  (name, description, email, facebook_link, twitter_link, copyright, primary_color, secondary_color, app_url, paypal_web_profile, payment_success_redirect_url, payment_cancelled_redirect_url, payment_failed_redirect_url, merchant_id, public_key, secret_key, is_active, domains, logo_url, icon_url, contact_us_url, smtp_server, smtp_port, smtp_username, smtp_password, created_at, updated_at)
VALUES
  ('Sports Kunekk', 'The app, the myth, and the legend', 'sports@kunekk.com', 'https://www.facebook.com/sportskunekk/', NULL, '&copy; 2018 Sports Kunekk. All rights reserved.', NULL, NULL, 'https://demo.tickets.enablr.co/merchant/starcity/purchase-summary/', 'XP-BMQA-3ZCW-BW68-8HYK', NULL, NULL, NULL, 'sportskunekk', NULL, NULL, TRUE, 'staging.tickets.splashisland.ph,staging.transport.splashisland.ph', NULL, 'https://staging.tickets.splashisland.ph/assets/img/splash-island-favicon.png', NULL, 'smtp.zoho.com', 465, 'infostaging@splashisland.ph', 'q57A3DbXHaLp', NOW(), NOW()),
  ('Splash Island Spa & Resort', 'The biggest waterpark on the Philippines', 'info@splashisland.ph', 'https://www.facebook.com/splashisland/', NULL, '&copy; 2018 Splash Island Spa & Resort', NULL, NULL, 'https://staging.tickets.splashisland.ph/purchase-summary/', 'XP-LT28-XTP8-JEGK-F6K6', NULL, NULL, NULL, 'splashisland', NULL, NULL, TRUE, 'staging.tickets.splashisland.ph,staging.transport.splashisland.ph', 'https://cdn.devkinetics.com/splash-island-logo-green-blue-300x300px.png', 'https://staging.tickets.splashisland.ph/assets/img/splash-island-favicon.png', NULL, 'smtp.zoho.com', 465, 'infostaging@splashisland.ph', 'q57A3DbXHaLp', NOW(), NOW()),
  ('Star City', 'Thinking of a weekend get-away that is affordable, close enough to home, and with something for everyone? Star City, housed within the CCP Complex in Pasay, is truly big on family fun.', 'info@starcity.com.ph', NULL, NULL, '&copy; 2018 Star City. All rights reserved.', NULL, NULL, 'https://demo.tickets.enablr.co/merchant/starcity/purchase-summary/', 'XP-Y43X-9NWT-N75U-PTSE', NULL, NULL, NULL, 'starcity', NULL, NULL, TRUE, 'staging.tickets.starcity.com.ph', 'https://www.starcity.com.ph/assets/images/logo_new.png', NULL, NULL, 'smtp.zoho.com', 465, 'infostaging@enablr.co', 'zm8wqba7ZT9Y', NOW(), NOW()),
  ('La Vista Pansol Resort', 'Take a soothing dip or have fun with your friends at La Vista Pansol''s over 7,000 square meters of crystal clear water, natural warm spring swimming pools and enjoy the amenities you would expect to find in a five star resort.', 'info@starcity.com.ph', NULL, NULL, '&copy; 2018 Star City. All rights reserved.', NULL, NULL, 'https://demo.tickets.enablr.co/merchant/lavistapansolresort/purchase-summary/', 'XP-Y43X-9NWT-N75U-PTSE', NULL, NULL, NULL, 'lavistapansolresort', NULL, NULL, TRUE, 'staging.tickets.lavistapansolresort.com', 'https://cdn.devkinetics.com/la-vista-logo.png', NULL, NULL, 'smtp.zoho.com', 465, 'infostaging@enablr.co', 'zm8wqba7ZT9Y', NOW(), NOW()),
  ('Dealr', NULL, 'info@starcity.com.ph', NULL, NULL, '&copy; 2018 Star City. All rights reserved.', NULL, NULL, 'https://demo.tickets.enablr.co/merchant/dealr', 'XP-LPFS-EYWC-S25D-KWGE', NULL, NULL, NULL, 'dealr', NULL, NULL, TRUE, 'demo.tickets.dealr.co', 'https://demo.tickets.enablr.co/assets/img/dealr-logo-120px.png', 'https://staging.dealr.co/images/dealr-favicon.png', NULL, 'smtp.zoho.com', 465, 'infostaging@dealr.co', '6cU3XtSq05fw', NOW(), NOW());
INSERT
INTO
  cfg_group
  (name, description, image, cover_photo, dialing_code, contact_number, latitude, longitude, currency, is_community, is_active, payment_gateway_1, payment_gateway_2, payment_gateway_3, payment_gateway_4, payment_gateway_5, payment_direct_bank_transfer_cash, payment_gateway_1_minimum_registration_fee, payment_direct_bank_transfer_cash_min_registration_fee)
VALUES
  ('DevKinetics Inc.', '...', 'https://image.com/124.png', 'https://image.com/124.png', NULL, NULL, 123.0, 123.0, NULL, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1, 1);